# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .docs/build/html
    - cp -r * .docs/build/html
    - mv .docs/build/html docs/build/html
  artifacts:
    paths:
      - docs/build/html
  only:
    - master
