stages:
  - deploy
  - static analysis

python-black:
  image: python:3.7-slim
  stage: static analysis
  script:
    - pip install black
    - black .

deploy_to_PyPI:
  image: python:3.7-slim
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload --repository-url $PYPI_REPOSITORY_URL dist/*
  only:
    - tags

deploy_to_Conda:
  image: continuumio/miniconda3:4.8.2
  stage: deploy
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - conda install conda-build anaconda-client
    - conda config --set anaconda_upload yes
    - conda config --append channels conda-forge
    - sed -i "s/covnet_version/$CI_COMMIT_TAG/g" conda-config/meta.yaml
    - conda-build --token $ANACONDA_PASSWORD conda-config
  only:
    - tags

pages:
  image: python:3.7-slim
  stage: deploy
  script:
    - apt update
    - apt install -y gcc
    - pip install sphinx recommonmark sphinx_rtd_theme numpy scipy
    - pip install obspy
    - sphinx-build -b html ./docs/source public
  artifacts:
    paths:
      - public
  only:
    - master